### PR TITLE
Update deprecated links

### PR DESCRIPTION
**Pull request by meli-lewis**
I used Internet Archive URLs for PDFs.

### CODE REVIEW

**Comment by iandees** [comment]
Thanks @meli-lewis! @JoeGermuska @ryanpitts how do these look?

**Comment by ryanpitts** [comment]
Looks great to me 👍 

Thank you @meli-lewis!

**Comment by JoeGermuska** [comment]
hm i was getting a security error for a minute on one of the Wayback links, but it's working for me now.  Thank you!

**Comment by ryanpitts** [comment]
yep I got the same error too, but worked on refresh

**Comment by JoeGermuska** [comment]
deployed!

**Pull request merged**
