### PR TITLE
start on code for previewing embeds

### PR DESCRIPTION
**Pull request by chrissyha**
work on #56 -- still some to do to show how changing the float affects the preview

### CODE REVIEW

**Comment by JoeGermuska** [comment]
Note to anyone who comes along: this is work in progress, but I encouraged @chrissyha to start the pull request as part of the WSC/Pyladies hack day, both to get practice and to put a flag in that this is something that is being worked on.

**Comment by JoeGermuska** [comment]
@chrissyha do you still have hopes to wrap this one up?

**Comment by chrissyha** [comment]
@JoeGermuska yes!!

**Comment by JoeGermuska** [comment]
@tuchandra @Joonpark13 If you guys pick this up, consider starting from this branch, although it looks like there are conflicts which could make that a hassle. I guess it may be easier to start from scratch?

**Comment by Joonpark13** [comment]
Obsoleted by PR #178.

**Comment by Joonpark13** [comment]
Obsoleted by PR #178.

**Pull request closed without merging**
